### ISSUE TITLE
Update days in year in today page copy operation

### ISSUE THREAD

**Issue by RDjarbeng** [RDjarbeng/countdown#128]
Today page has the day of year hardcoded as 365 when copying the day of year.

Needs to fix by using the `countDays`() function in class `NewYearClock`

Current behaviour: Day of the year shows the  hardcoded value of 365 for days in a year on leap years instead of 366
Expected behaviour: Day of the year should be the correct number of days in the year if it is or isn't a leap year (365 or 366)

**Comment by I-Vishal-Kumar** [comment]
assign me this issue

**Comment by RDjarbeng** [comment]
Hello Vishal, I can't find you to assign you to the issue. I am not sure if
you deleted the comment

**Comment by RDjarbeng** [comment]
Fixed in #132
