### ISSUE TITLE
Netlify CI/CD for all branches

### ISSUE THREAD

**Issue by nyakotey** [RDjarbeng/countdown#22]
Currently Netlify only deploys the master/production branch
@RDjarbeng Please set continuous deployment for all branches, to enable ease in testing experimental features happening on other branches

**Comment by RDjarbeng** [comment]
It deploys all branches, and even every commit, have you not seen the
netlify bot preview message

**Comment by RDjarbeng** [comment]
![image](https://user-images.githubusercontent.com/57795443/147675949-4a190a80-002d-421f-b94b-28cd9cdfdc52.png)

I have added the branch 'nat' but don't seem to get any preview

**Comment by RDjarbeng** [comment]
Ok working now, you have to push something first. Seems it won't automatically deploy the moment the branch is added

**Comment by nyakotey** [comment]
welldone

**Comment by RDjarbeng** [comment]
Here's the link for the [nat branch](https://nat--rcountdown.netlify.app/)
https://nat--rcountdown.netlify.app/
