### ISSUE TITLE
Make site exciting to watch

### ISSUE THREAD

**Issue by RDjarbeng** [RDjarbeng/countdown#28]
Add animations, transitions (not too much) to make clock interesting to watch

**Comment by nyakotey** [comment]
have you found a `.gif` you would want to use for the animated background?

**Comment by RDjarbeng** [comment]
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" width="1440" height="560" preserveAspectRatio="none" viewBox="0 0 1440 560">
    <g mask="url(&quot;#SvgjsMask1003&quot;)" fill="none">
        <rect width="1440" height="560" x="0" y="0" fill="rgba(23, 8, 50, 1)"></rect>
        <path d="M1382.406,518.779C1403.524,519.253,1421.942,504.944,1431.779,486.251C1440.97,468.787,1439.261,447.679,1428.543,431.108C1418.692,415.877,1400.526,410.739,1382.406,409.915C1362.23,408.997,1338.964,409.352,1328.376,426.551C1317.481,444.248,1326.221,466.187,1336.726,484.119C1347.081,501.795,1361.925,518.32,1382.406,518.779" fill="rgba(28, 83, 142, 0.4)" class="triangle-float1"></path>
        <path d="M413.13 321.04 a158.72 158.72 0 1 0 317.44 0 a158.72 158.72 0 1 0 -317.44 0z" fill="rgba(28, 83, 142, 0.4)" class="triangle-float2"></path>
        <path d="M417.379,198.748C437.502,198.108,453.675,184.798,464.483,167.812C476.374,149.124,486.551,126.253,475.843,106.863C464.905,87.056,439.921,80.567,417.379,82.514C397.987,84.189,384.082,98.919,374.135,115.65C363.889,132.884,355.526,153.198,364.782,170.984C374.591,189.833,396.141,199.424,417.379,198.748" fill="rgba(28, 83, 142, 0.4)" class="triangle-float2"></path>
        <path d="M804.23 285.12 a172.72 172.72 0 1 0 345.44 0 a172.72 172.72 0 1 0 -345.44 0z" fill="rgba(28, 83, 142, 0.4)" class="triangle-float3"></path>
        <path d="M395.62 2.55 a149.09 149.09 0 1 0 298.18 0 a149.09 149.09 0 1 0 -298.18 0z" fill="rgba(28, 83, 142, 0.4)" class="triangle-float3"></path>
        <path d="M22.97 341.67 a133.39 133.39 0 1 0 266.78 0 a133.39 133.39 0 1 0 -266.78 0z" fill="rgba(28, 83, 142, 0.4)" class="triangle-float2"></path>
        <path d="M663 125.82 a123.48 123.48 0 1 0 246.96 0 a123.48 123.48 0 1 0 -246.96 0z" fill="rgba(28, 83, 142, 0.4)" class="triangle-float2"></path>
    </g>
    <defs>
        <mask id="SvgjsMask1003">
            <rect width="1440" height="560" fill="#ffffff"></rect>
        </mask>
        <style>
            @keyframes float1 {
                0%{transform: translate(0, 0)}
                50%{transform: translate(-10px, 0)}
                100%{transform: translate(0, 0)}
            }

            .triangle-float1 {
                animation: float1 5s infinite;
            }

            @keyframes float2 {
                0%{transform: translate(0, 0)}
                50%{transform: translate(-5px, -5px)}
                100%{transform: translate(0, 0)}
            }

            .triangle-float2 {
                animation: float2 4s infinite;
            }

            @keyframes float3 {
                0%{transform: translate(0, 0)}
                50%{transform: translate(0, -10px)}
                100%{transform: translate(0, 0)}
            }

            .triangle-float3 {
                animation: float3 6s infinite;
            }
        </style>
    </defs>
</svg>

**Comment by RDjarbeng** [comment]
Raw svg code from bgjar.com trust you can take it from here

**Comment by nyakotey** [comment]
@RDjarbeng , the code you pasted is incomplete.
