### ISSUE TITLE
50% background gradient not showing distinctly in light mode

### ISSUE THREAD

**Issue by RDjarbeng** [RDjarbeng/countdown#31]
Difficult to see that nice border and gradient with the 2 colors on light mode

![image](https://user-images.githubusercontent.com/57795443/147824277-c1a10b7e-31c7-45b7-949b-e2f253948850.png)

**Comment by nyakotey** [comment]
on it

**Comment by nyakotey** [comment]
resolved in #27 commit 481d62d
