### ISSUE TITLE
Author page icon alignment

### ISSUE THREAD

**Issue by RDjarbeng** [RDjarbeng/countdown#45]
Authors (contact us) page in #40 should be consistent.
![image](https://user-images.githubusercontent.com/57795443/152258140-5c6dd703-f1b5-449f-832f-8556606940b5.png)

Prefer icon on left with name on right.

**Comment by nyakotey** [comment]
@RDjarbeng, you know the `stylesheet` you used for this page belongs to `index.html` and so any changes made to it affects the `author page` either negatively or postively
Anyways, a fix has been made. 
Closing the issue now
